/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  cleiton
 * Created: 10/04/2017
 */
DROP DATABASE ERPROSATRAPO;

CREATE DATABASE ERPROSATRAPO;

USE ERPROSATRAPO;

CREATE TABLE PRODUTO(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESCRICAO VARCHAR(255),
QUANTIDADE INT,
PRECO DOUBLE
);


CREATE TABLE CLIENTE(
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(255),
DATANASCIMENTO DATE,
CPF VARCHAR(11),
TELEFONE VARCHAR(10),
CELULAR VARCHAR(11),
EMAIL VARCHAR(255),
RUA VARCHAR(255),
NUMERO INT,
COMPLEMENTO INT,
BAIRRO VARCHAR(255),
CIDADE VARCHAR(255),
CEP VARCHAR(8)
);
