/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;
import service.ClienteServiceImpl;

/**
 *
 * @author cleiton
 */
public class TelaPesquisaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAlteraCliente
     */
    public TelaPesquisaCliente() {
        initComponents();
        atualisaTabela();
    }
    public void atualisaTabela() {
        DefaultTableModel model = (DefaultTableModel) tblClientes.getModel();
        model.setNumRows(0);
        ClienteServiceImpl service = new ClienteServiceImpl();

        service.getAllClientes().forEach((p) -> {
            model.addRow(new Object[]{p.getId(),
                p.getNome(),
                p.getCpf(),
                });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelAlteraCliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnAlteraCliente = new javax.swing.JButton();
        btnExcluiCliente = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();
        txtPesquisaCpf = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        btnAlteraCliente.setText("Alterar");

        btnExcluiCliente.setText("Excluir");

        btnPesquisa.setText("Pesquisa Cpf");

        javax.swing.GroupLayout painelAlteraClienteLayout = new javax.swing.GroupLayout(painelAlteraCliente);
        painelAlteraCliente.setLayout(painelAlteraClienteLayout);
        painelAlteraClienteLayout.setHorizontalGroup(
            painelAlteraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
            .addGroup(painelAlteraClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesquisa)
                .addGap(49, 49, 49)
                .addComponent(txtPesquisaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(painelAlteraClienteLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(btnAlteraCliente)
                .addGap(47, 47, 47)
                .addComponent(btnExcluiCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelAlteraClienteLayout.setVerticalGroup(
            painelAlteraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlteraClienteLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(painelAlteraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisa)
                    .addComponent(txtPesquisaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAlteraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlteraCliente)
                    .addComponent(btnExcluiCliente))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAlteraCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelAlteraCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlteraCliente;
    private javax.swing.JButton btnExcluiCliente;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelAlteraCliente;
    private javax.swing.JTable tblClientes;
    private javax.swing.JFormattedTextField txtPesquisaCpf;
    // End of variables declaration//GEN-END:variables
}
